# Generated by Django 2.0.1 on 2018-01-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20171229_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_name', models.CharField(max_length=100)),
                ('creator_card', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Book',
            new_name='Vcard',
        ),
        migrations.DeleteModel(
            name='Writer',
        ),
        migrations.RenameField(
            model_name='vcard',
            old_name='name_book',
            new_name='name_card',
        ),
        migrations.RenameField(
            model_name='vcard',
            old_name='price_book',
            new_name='price_card',
        ),
    ]
