# Generated by Django 2.0.1 on 2018-01-14 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('creator_id', models.AutoField(primary_key=True, serialize=False)),
                ('creator_name', models.CharField(max_length=100, verbose_name='Производитель')),
                ('creator_cnt', models.CharField(max_length=100, verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id_human', models.AutoField(primary_key=True, serialize=False)),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('code_order', models.CharField(max_length=45, verbose_name='Код регистрации')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Vcard',
            fields=[
                ('id_card', models.AutoField(primary_key=True, serialize=False)),
                ('card_name', models.CharField(max_length=45, verbose_name='Название видеокарты')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('card_price', models.CharField(max_length=15, verbose_name='Цена')),
                ('card_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.Creator', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Видеокарта',
                'verbose_name_plural': 'Видеокарта',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='card_order',
            field=models.ManyToManyField(to='my_app.Vcard', verbose_name='Выбранная видеокарта'),
        ),
        migrations.AddField(
            model_name='human',
            name='order_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.Order', verbose_name='Код заказа'),
        ),
    ]
